extends Node

@warning_ignore("unused_signal")
signal team_scored(country_scored_on: String)
@warning_ignore("unused_signal")
signal score_changed()
@warning_ignore("unused_signal")
signal team_reset()
@warning_ignore("unused_signal")
signal kickoff_ready()
@warning_ignore("unused_signal")
signal kickoff_started()
@warning_ignore("unused_signal")
signal ball_carried(carrier_name: String)
@warning_ignore("unused_signal")
signal ball_released()
